### ISSUE TITLE
Docs: Windows External Tools setup does not work as described

### ISSUE THREAD

**Issue by daffodildil** [grndctrl/zed-gdscript#73]
_Maintainer edit: This seems to be related to a bug or regression in Zed, here's a pull request that aims to address the issue in Zed's repository: https://github.com/zed-industries/zed/pull/47730. Thanks @cozybuild for the link!_

---

In the following section of the readme.md related to setting up zed as an External Editor and configuring Godot's Exec Flags and the zed Exec Path:

```
Opening GDScript files in Zed instead of Godot

If you want to open GDScript files in Zed instead of Godot, you need to change Godot editor settings. In the Godot editor, go to Editor > Editor Settings > Text Editor > External and enable Use External Editor. Set the Exec Path to the path of your Zed executable and the Exec Flags to {project} {file}:{line}:{col}. This will open files and jump to the correct line in Zed when you click on an error or warning in Godot.
```

These steps do not work for me on Windows 10.
If I set the Godot External Editor Exec Path to the path of zed's executable itself, then the Exec Flags as written do not properly open the files. 
Zed launches but no script is selected.
If I changed the Exec Flags to `{project} {file}` then the file launches when I double click on it in the godot editor.

If I change the Exec Path from the actual file path, to just `zed` then the Exec flags described in the readme work correctly.

**Comment by jactor2** [comment]
I can confirm this works. ReadMe should be updated. However, do note that zed needs to be added to PATH in system variables, you can check by typing 'zed' inside powershell or CMD, if it is recognized it should open up zed directly.

**Comment by jrohlandt** [comment]
Can confirm the same steps fixes the issue on MacOS. Thanks @daffodildil and @jactor2

**Comment by NathanLovato** [comment]
Thanks for the link @cozybuild, I added it to the first post for reference.

**Comment by jansteffen** [comment]
The issue in Zed is now resolved and using ```{project} {file}:{line}:{col}``` as Exec Flags on Windows now works as expected.

**Comment by NathanLovato** [comment]
Thanks for letting me know!

**Comment by pegasusearl** [comment]
It's still not resolved for me. I still have to remove `:{line}:{col}`

It will work if Zed not already opened, but if Zed is already opened, it will simply switch window to Zed but it will not open the correct file.
However if I ran the command manually in terminal, there is no problem.

I wonder if it's Godot problem or Zed problem.

https://github.com/user-attachments/assets/e5cf54e3-9e1e-4bbe-bdea-dccc3c9fa148

```
Godot v4.8.dev2 - Windows 11 (build 26100) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 4060 (NVIDIA; 32.0.15.6636) - Intel(R) Core(TM) Ultra 7 265K (20 threads) - 47.27 GiB memory - WASAPI (48000 Hz, Stereo/mono)

Zed 1.16.1 
Commit: eb8e1c8b5502b7007465fbbc465f4a736fa39210
Version: 1.16.1+stable.343.eb8e1c8b5502b7007465fbbc465f4a736fa39210
```

# The fix.

My earlier Exec Path was this: `C:/Users/<user>/AppData/Local/Programs/Zed/Zed.exe`
It's fixed by changing it to `C:/Users/<user>/AppData/Local/Programs/Zed/bin/zed.exe`

I wasn't sure which docs you mentioned in this discussion so I can't verify if I was doing it right in the beginning. But if it was Godot Docs, there is no information about Exec Path for zed so I thought I could just use the same Exe to load the gui app. Looks like that's not the case, `bin/zed.exe` is the dedicated command line shim and should be used.

Running through terminal worked because `zed` pointed to `bin/zed.exe`. I should have check `which zed` instead of grabbing the GUI executable. **I wonder if this is common knowledge for programmers?** Windows doesn't have `which` command though.

**Comment by NathanLovato** [comment]
Glad if you could find the right binary to run. I will let Windows users chime in in case this is a systematic problem and Zed does ship with multiple binaries on Windows. On Linux, it's not the case. We have a single binary for running Zed as a graphical application or to invoke it from the command line.

I wouldn't say any of this kind of knowledge of how to execute a specific program is common or natural to programmers. What happens more is people figure it out by running the program's help and testing commands, then they don't necessarily take the time to document for others.

Also, the way you run the program or configure it can change your versions sometimes due to regressions or through evolutions of the program for some reason that you just don't catch, or you simply don't know, or you don't remember to test and document.
